version: '3.8'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "API_ID=76bb4628d69dc077e37fa169a58eeebb"
      - "DJANGO_SECRET_KEY=django-insecure-l3(=mxcy(dp3j^laap&k-1g&+kyz3n_)&h^&bw-3#7^3c27eup"
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
